### ISSUE TITLE
Readme "I want to control with Mouse and Keyboard!!" section is missing step 3

### ISSUE THREAD

**Issue by TorMechia** [Kelkador/Kid-Icarus-AHK-Scripts#1]
![Screenshot 2021-07-16 at 17-03-55 Kelkador Kid-Icarus-AHK-Scripts](https://user-images.githubusercontent.com/56943516/126008349-995b6c01-d4d6-4f89-9569-44c6390c0963.png)

I _believe_ step three was meant to be about downloading UCR.ini from the GitHub page.

**Comment by Kelkador** [comment]
Yeah, that was just the result of staying up WAYWAYWAY too late and not proofreading. Step 3 is nothing, as it is assumed you download everything at the start of the tutorial. Updated the numbering for the steps to cause less confusion. Thank you!
