### ISSUE TITLE
Instructions (genuinely) Unclear?

### ISSUE THREAD

**Issue by Fivavoa** [Kelkador/Kid-Icarus-AHK-Scripts#3]
I'm a dumb idiot moron idiot, but I'm completely lost on how this is supposed to work. I downloaded everything, followed the instructions afaik by:
Downloading everything
Setting up Citra first and keeping it open with KI:U running
Click on Generator.bat and follow those (for some reason it kept asking for joyx and joyy ahk, but then stopped? I noticed in Lib it ended up showing up in there eventually somehow, not sure how but the script stopped saying it wasn't there anymore)
I doubleclick the generated KeyboardMouse.ahk that it made and... nothing happens. I tried re-reading the guide but maybe I'm missing something? Like in the guide, it says "Create your own MouseKeyboard.ahk file" does it mean to use the generator or make my own AHK? I've never used it before so I have no idea what I'm doing, so apologies if these have very obvious solutions.

**Comment by Kelkador** [comment]
Hey there! If you could answer these two questions for me that’d be great.

1. Are you pressing the key you set to start the script in generate.bat?
2. If you are, do you have .NetFramework installed? I missed that as a dependency.

I wrote the updated guide sleep deprived so I’ll give it another look after tonight, thanks!

**Comment by Fivavoa** [comment]
Heya, thanks for the quick response!

I surprisingly didn't have .Net 4 installed, and I ended up having to change the hotkey for start/stop script since it didn't really like using a numpad key. Seems to work now, however, it still won't let me move. According to the guide, you mentioned that it auto-maps WASD to the joystick? Either way, at least the mouse is being captured so some progress is being made!

**Comment by Kelkador** [comment]
Can you show me a pic of the file structure in the main folder, as well as attaching JoyY.ahk and JoyX.ahk ?

**Comment by Fivavoa** [comment]
Sure.
Root folder:
![image](https://github.com/Kelkador/Kid-Icarus-AHK-Scripts/assets/29827600/b9773752-a9e1-4900-8fec-b1fc8e979817)
And then the ahk files:
[Lib.zip](https://github.com/Kelkador/Kid-Icarus-AHK-Scripts/files/13255483/Lib.zip)

**Comment by Kelkador** [comment]
hm, can you double check you binded the controller correctly in Citra? Also
would like to confirm you downloaded the files from releases and didn’t
just yoink the generate.bat from source?

**Comment by Fivavoa** [comment]
Here is how the controller binds work, it's possible I misunderstood something:
![image](https://github.com/Kelkador/Kid-Icarus-AHK-Scripts/assets/29827600/1c09f2f0-96cd-4913-9d26-acf152db2a78)

Also I'm pretty sure I got it from releases but I don't fully remember unfortunately.

**Comment by Kelkador** [comment]
Go to win control panel and search for “Set Up USB Game Controllers” check that when you open MouseKeyboard.ahk a controller shows up.

**Comment by Fivavoa** [comment]
Seems like a Controller does show up:
![image](https://github.com/Kelkador/Kid-Icarus-AHK-Scripts/assets/29827600/c7c607e2-5995-4c42-992b-53ae8e178f2c)
I messed around in properties and WASD is being detected on the joystick based off the inputs, but on citra itself it doesn't register anything.

**Comment by Fivavoa** [comment]
Quick Addendum: 
I just re-setup the defaults for Citra and now it's detecting everything! I don't know why it didn't do that the last few times but I guess it now works. The last thing to acknowledge is that is it intentional for joystick movement to be so delayed and laggy? I recall on your guide was to get AHK 1.1 and not the newer 2.0 right? Unsure how it would go but a quick test makes it really difficult to even shoot and move at the same time. The mouse controls work pretty perfectly but there's a lot of occasions where it gets extra delayed if I even shoot. Has about half a second of input lag without shooting and with shooting the inputs can occasionally straight up drop.

**Comment by Fivavoa** [comment]
![output](https://github.com/Kelkador/Kid-Icarus-AHK-Scripts/assets/29827600/6b9d4165-88eb-4b41-a14b-a1a492e16064)

Seems like there's significant processing anytime the fire button is pressed at all. Otherwise the joystick movement is very gradual so it's difficult to even sprint in the game like this.

**Comment by Kelkador** [comment]
I updated Generator.bat to provide less sluggish controls, and remember if you want to sprint you can always use the sprint modifier you set while generating!

**Comment by Fivavoa** [comment]
Ah awesome, I thought that was jump for some reason, I haven't played KI:U in a hot minute. Otherwise I think it's all good. Did a small playtest today and it went by okay, unsure if it's user error at this point or what but there's still a lot of random input issues. For example, it doesn't handle quick inputs well (so trying to go to full stop to try to do dodges is very difficult) or movement straight up unable to be read at all (inputting diagonals, switching from sprint to regular run often, etc) randomly requiring a wait period until the inputs work again and I'm unsure why. 
However, I'm sure it's just due to limitations of AHK or something. Either way, the script itself mostly works, so thanks for the help! Sorry there didn't turn out to be much actual issues and things just randomly worked after re-doing things after a while. Very much appreciated.
